#!/usr/bin/env bash
# omega_tampermonkey.sh — Browser extension setup for Instagram automation
set -euo pipefail

PROJECT="/root/Documents/Codex/2026-06-08/make-the-deepseek-v4-flash-free"
OMEGA="$PROJECT/omega"

echo "Ω Omega Tampermonkey Setup"
echo ""
echo "Tampermonkey script ready at:"
echo "  omega/scripts/instagram_auto_liker.user.js"
echo ""
echo "To install:"
echo "  1. Install Tampermonkey extension in your browser:"
echo "     https://www.tampermonkey.net/"
echo ""
echo "  2. Install Cookie-Editor extension:"
echo "     https://cookie-editor.com/"
echo ""
echo "  3. Open the script in your browser:"
echo "     file://$OMEGA/scripts/instagram_auto_liker.user.js"
echo "     Tampermonkey will detect it and prompt to install."
echo ""
echo "  4. For Cookie-Editor export:"
echo "     Export cookies as JSON, then import via Python:"
echo ""
echo "     python3 << 'EOF'"
echo "     import json"
echo "     with open('cookies.json') as f:"
echo "         cookies = json.load(f)"
echo "     # Cookies can be loaded into Playwright session"
echo "     page.context.add_cookies(cookies)"
echo "     print(f'Loaded {len(cookies)} cookies')"
echo "     EOF"
echo ""
echo "  5. Or run the sloth bot directly:"
echo "     omega sloth"
