project_id = "uakkwvdjoqsceewhsfjb"

[functions.ai-chat]
verify_jwt = false

[functions.generate-outfits]
verify_jwt = false

[functions.analyze-item]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.analyze-outfit]
verify_jwt = false

[functions.analyze-style-dna]
verify_jwt = false

[functions.find-similar]
verify_jwt = false

[functions.shop-products]
verify_jwt = false
