import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "@phosphor-icons/react";

const Privacy = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 py-16">
        <motion.button
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-10 font-sans text-sm"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to home
        </motion.button>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="font-display text-4xl font-bold text-foreground mb-2">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground font-sans mb-8">Last updated: July 19, 2026</p>

          <div className="prose prose-invert max-w-none font-sans text-sm leading-relaxed space-y-6 text-muted-foreground">
            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">1. Information We Collect</h2>
              <p>LUXOR® collects information you provide directly and information generated through your use of the service:</p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li><strong className="text-foreground">Account Information:</strong> Email address, display name, and authentication credentials when you create an account.</li>
                <li><strong className="text-foreground">Wardrobe Data:</strong> Photos of clothing items you upload, outfit compositions, and style preferences you provide during onboarding.</li>
                <li><strong className="text-foreground">Style Profile:</strong> Your body shape, face shape, color analysis results, and fashion preferences generated by our AI.</li>
                <li><strong className="text-foreground">Usage Data:</strong> Pages visited, features used, interactions with the app, and device information (browser type, screen size, general location).</li>
                <li><strong className="text-foreground">Payment Information:</strong> Processed entirely by PayPal. We never store your credit card number or financial details on our servers.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">2. How We Use Your Information</h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>To provide, maintain, and improve the LUXOR® AI styling service.</li>
                <li>To train and improve our AI models for outfit recommendations, color analysis, and style predictions.</li>
                <li>To personalize your experience and deliver daily outfit suggestions.</li>
                <li>To process payments and manage your subscription.</li>
                <li>To send you service-related emails (account security, subscription updates). We never send marketing emails without explicit consent.</li>
                <li>To detect and prevent fraud, abuse, and security incidents.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">3. AI & Machine Learning</h2>
              <p>Your wardrobe photos and style preferences may be used to train our AI models. This training data is anonymized and aggregated — it cannot be traced back to your individual account. You can request deletion of your training data at any time by contacting us.</p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">4. Data Sharing</h2>
              <p>We do not sell your personal data. We share information only with:</p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li><strong className="text-foreground">Infrastructure Providers:</strong> Supabase (database), Vercel (hosting), and PayPal (payments) — all bound by strict data processing agreements.</li>
                <li><strong className="text-foreground">Analytics:</strong> Vercel Speed Insights and Facebook Pixel for performance monitoring and conversion tracking. These tools receive anonymized usage data.</li>
                <li><strong className="text-foreground">Legal Requirements:</strong> When required by law, subpoena, or to protect the safety of our users.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">5. Data Security</h2>
              <p>We implement industry-standard security measures including encryption in transit (TLS 1.3), encryption at rest, role-based access controls, and Row-Level Security (RLS) on all database tables. However, no method of transmission over the Internet is 100% secure.</p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">6. Your Rights</h2>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong className="text-foreground">Access:</strong> Request a copy of all data we hold about you.</li>
                <li><strong className="text-foreground">Deletion:</strong> Request permanent deletion of your account and all associated data.</li>
                <li><strong className="text-foreground">Portability:</strong> Export your wardrobe data in a standard format.</li>
                <li><strong className="text-foreground">Opt-Out:</strong> Request that your data not be used for AI training.</li>
              </ul>
              <p className="mt-2">To exercise any of these rights, email us at privacy@luxor.ly.</p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">7. Data Retention</h2>
              <p>We retain your account data for as long as your account is active. Upon account deletion, we remove all personal data within 30 days, except where required by law or for fraud prevention (up to 12 months).</p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">8. Children's Privacy</h2>
              <p>LUXOR® is not intended for users under 16. We do not knowingly collect data from children. If you believe a child has provided us with personal data, contact us immediately.</p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">9. Changes to This Policy</h2>
              <p>We may update this policy from time to time. We will notify you of material changes via email or in-app notification at least 30 days before they take effect.</p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-foreground mb-3">10. Contact Us</h2>
              <p>For privacy-related inquiries: <span className="text-foreground">privacy@luxor.ly</span></p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default Privacy;
